### PR TITLE
iopay

### PR DESCRIPTION
**Pull request by GiupiDeLuca**
added iopay contract and sdk

### CODE REVIEW

**Review by tomteman — DISMISSED** [review]

**Comment by tomteman** [comment]
Please remove yarn.lock from your commit

**Comment by GiupiDeLuca** [comment]
hey @tomteman I just removed the yarn.lock - thank you

**Comment by tomteman** [comment]
@GiupiDeLuca not delete yarn.lock from the codebase, but don't commit whatever local changes you have made to yarn.lock in your PR

**Comment by GiupiDeLuca** [comment]
@tomteman pardon the confusion, I "re-added" the yarn.lock file in the original version! Thanks again 🙌

**Pull request merged**
